### ISSUE TITLE
Gnome 43 Crash

### ISSUE THREAD

**Issue by ghost** [Selenium-H/App-Grid-Tweaks#22]
Hi,

Last week when I upgraded gnome to v43, App-Grid was too glitchy and reversed to 5x5 grid even when the extension is enabled.

Can you please upgrade your extension to be compatble with Gnome 43 :smile:

**Comment by ragnarokxg** [comment]
I second this, even tweaking the app to work on 43 still getting a "MainAppDisplay.adaptToSize is not a function" error

**Comment by raihan2000** [comment]
@ragnarokxg comment this lines and see, I could not figure out how can I resize grid like old version?
cuz I'm not familier with javascript
```
//this.defaultAdaptToSizeFunction = MainAppDisplay.adaptToSize;
//MainAppDisplay.adaptToSize = this.overriddenAdaptToSizeFunction;
```
and ```//MainAppDisplay.adaptToSize = this.defaultAdaptToSizeFunction;``` on undochange() function

**Comment by ghost** [comment]
Didn't work!

I think this extension need to be rewritten from scratch for Gnome v43 otherwise I don't see how it would work

**Comment by raihan2000** [comment]
@jJit0  checkout [this repo](https://github.com/raihan2000/App-Grid-Tweaks) and comment out those lines and see I think it will work

**Comment by ghost** [comment]
Ok so after many tests, it seems the problem is not really related to App-Grid-Tweaks extension.

The thing is when you remove the Workspace boxes from the AppGrid thanks to JustPerfection extension, it creates a shadowed distorted boxes that affects rows and lines of the AppGrid.

It seems there is an open issue for that, but the author of JustPerfection didn't respond yet. We'll just have to wait for a solution.

**Comment by Tuxman2** [comment]
Hi, 

thanks to try to support Gnome 42 and Gnome 43. The locale files are missing. Can someone here add the translation support ? The extension is not translated in other languages.

Thanks.

**Comment by alesya-h** [comment]
For me it is just broken on Gnome 43 - the grid doesn't change, or change weirdly, but not according to the grid configuration, the extension crash when disabling, any kind of config editing only can be applied by logout-login, etc etc. Not really usable. And I don't have Just Perfection enabled, so it's not because of it.

**Comment by ghost** [comment]
Hey Alesya,
I don't know why it's not working for you, but let me show you my settings and my app grid, proof that it's working for me
https://imgur.com/a/ESKEmMd
https://imgur.com/euihVPM

**Comment by Gnomeknilch** [comment]
Hi all,
this App have Bug. started my system new, app is correct. login on GDM and start the desktop, app work correct. Closed the display on my notebook (suspend, sleep), works app not correct. this info is error:  "MainAppDisplay.adaptToSize is not a function" … 
my System: 
Gnome 43 + App-Grid-Tweak 4 
i'm tested this : https://github.com/Selenium-H/App-Grid-Tweaks/issues/22#issuecomment-1290963264 … and other infos, no way out!

Edit: i love this app, this tool is wunderful. Gnome (43) is a great desktop, this icons by app grid to big and ugly. this app-grid-tweak make gnome desktop very greatful.

**Comment by Tuxman2** [comment]
Hi,

Can anyone here support this extension in order to have a working version for Gnome 43 and above ?

This project seems to be stalled for now.

Thanks.

**Comment by Tuxman2** [comment]
Hello,

As the project seems to be stalled for now, I found an other alternative to be able to change the applications grid (icon size, ....). It is the Gnome shell extension : V-Shell (Vertical Workspaces). With it you can do many things , as for example, adjust the applications grid. Here is the link: https://extensions.gnome.org/extension/5177/vertical-workspaces/
Here more information about the features: https://github.com/G-dH/vertical-workspaces

Regards.

**Comment by stoneC0der** [comment]
V-Shell does not work with Gnome 44.3, at least on my system Ubuntu 23.04, black screen after login when using xorg (Nvidia).
I plan on going through the this extension code to see if I can make it work, however I never build an extension for gnome, but I know JavaScript a bit
